export const BOOKING_GET_LOADING = "BOOKING_GET_LOADING";
export const BOOKING_GET_ERROR = "BOOKING_GET_ERROR";
export const BOOKING_GET_SUCCESS = "BOOKING_GET_SUCCESS";

export const BOOKING_GET_BY_ID_LOADING = "BOOKING_GET_BY_ID_LOADING";
export const BOOKING_GET_BY_ID_ERROR = "BOOKING_GET_BY_ID_ERROR";
export const BOOKING_GET_BY_ID_SUCCESS = "BOOKING_GET_BY_ID_SUCCESS";

export const BOOKING_POST_LOADING = "BOOKING_POST_LOADING";
export const BOOKING_POST_ERROR = "BOOKING_POST_ERROR";
export const BOOKING_POST_SUCCESS = "BOOKING_POST_SUCCESS";

export const BOOKING_UPDATE_LOADING = "BOOKING_UPDATE_LOADING";
export const BOOKING_UPDATE_ERROR = "BOOKING_UPDATE_ERROR";
export const BOOKING_UPDATE_SUCCESS = "BOOKING_UPDATE_SUCCESS";

// export const BOOKING_DELETE_LOADING = "BOOKING_DELETE_LOADING";
// export const BOOKING_DELETE_ERROR = "BOOKING_DELETE_ERROR";
// export const BOOKING_DELETE_SUCCESS = "BOOKING_DELETE_SUCCESS";