export const CUSTOMER_GET_LOADING = "CUSTOMER_GET_LOADING";
export const CUSTOMER_GET_ERROR = "CUSTOMER_GET_ERROR";
export const CUSTOMER_GET_SUCCESS = "CUSTOMER_GET_SUCCESS";

export const CUSTOMER_GET_BY_ID_LOADING = "CUSTOMER_GET_BY_ID_LOADING";
export const CUSTOMER_GET_BY_ID_ERROR = "CUSTOMER_GET_BY_ID_ERROR";
export const CUSTOMER_GET_BY_ID_SUCCESS = "CUSTOMER_GET_BY_ID_SUCCESS";

export const CUSTOMER_POST_LOADING = "CUSTOMER_POST_LOADING";
export const CUSTOMER_POST_ERROR = "CUSTOMER_POST_ERROR";
export const CUSTOMER_POST_SUCCESS = "CUSTOMER_POST_SUCCESS";

export const CUSTOMER_UPDATE_LOADING = "CUSTOMER_UPDATE_LOADING";
export const CUSTOMER_UPDATE_ERROR = "CUSTOMER_UPDATE_ERROR";
export const CUSTOMER_UPDATE_SUCCESS = "CUSTOMER_UPDATE_SUCCESS";

export const CUSTOMER_DELETE_LOADING = "CUSTOMER_DELETE_LOADING";
export const CUSTOMER_DELETE_ERROR = "CUSTOMER_DELETE_ERROR";
export const CUSTOMER_DELETE_SUCCESS = "CUSTOMER_DELETE_SUCCESS";