export const EMPLOYEE_GET_LOADING = "EMPLOYEE_GET_LOADING";
export const EMPLOYEE_GET_ERROR = "EMPLOYEE_GET_ERROR";
export const EMPLOYEE_GET_SUCCESS = "EMPLOYEE_GET_SUCCESS";

export const EMPLOYEE_GET_BY_ID_LOADING = "EMPLOYEE_GET_BY_ID_LOADING";
export const EMPLOYEE_GET_BY_ID_ERROR = "EMPLOYEE_GET_BY_ID_ERROR";
export const EMPLOYEE_GET_BY_ID_SUCCESS = "EMPLOYEE_GET_BY_ID_SUCCESS";

export const EMPLOYEE_POST_LOADING = "EMPLOYEE_POST_LOADING";
export const EMPLOYEE_POST_ERROR = "EMPLOYEE_POST_ERROR";
export const EMPLOYEE_POST_SUCCESS = "EMPLOYEE_POST_SUCCESS";

export const EMPLOYEE_UPDATE_LOADING = "EMPLOYEE_UPDATE_LOADING";
export const EMPLOYEE_UPDATE_ERROR = "EMPLOYEE_UPDATE_ERROR";
export const EMPLOYEE_UPDATE_SUCCESS = "EMPLOYEE_UPDATE_SUCCESS";

export const EMPLOYEE_DELETE_LOADING = "EMPLOYEE_DELETE_LOADING";
export const EMPLOYEE_DELETE_ERROR = "EMPLOYEE_DELETE_ERROR";
export const EMPLOYEE_DELETE_SUCCESS = "EMPLOYEE_DELETE_SUCCESS";