export const TESTDRIVE_GET_LOADING = "TESTDRIVE_GET_LOADING";
export const TESTDRIVE_GET_ERROR = "TESTDRIVE_GET_ERROR";
export const TESTDRIVE_GET_SUCCESS = "TESTDRIVE_GET_SUCCESS";

export const TESTDRIVE_GET_BY_ID_LOADING = "TESTDRIVE_GET_BY_ID_LOADING";
export const TESTDRIVE_GET_BY_ID_ERROR = "TESTDRIVE_GET_BY_ID_ERROR";
export const TESTDRIVE_GET_BY_ID_SUCCESS = "TESTDRIVE_GET_BY_ID_SUCCESS";

export const TESTDRIVE_POST_LOADING = "TESTDRIVE_POST_LOADING";
export const TESTDRIVE_POST_ERROR = "TESTDRIVE_POST_ERROR";
export const TESTDRIVE_POST_SUCCESS = "TESTDRIVE_POST_SUCCESS";

export const TESTDRIVE_UPDATE_LOADING = "TESTDRIVE_UPDATE_LOADING";
export const TESTDRIVE_UPDATE_ERROR = "TESTDRIVE_UPDATE_ERROR";
export const TESTDRIVE_UPDATE_SUCCESS = "TESTDRIVE_UPDATE_SUCCESS";

// export const TESTDRIVE_DELETE_LOADING = "TESTDRIVE_DELETE_LOADING";
// export const TESTDRIVE_DELETE_ERROR = "TESTDRIVE_DELETE_ERROR";
// export const TESTDRIVE_DELETE_SUCCESS = "TESTDRIVE_DELETE_SUCCESS";