export const TRANSACTION_GET_LOADING = "TRANSACTION_GET_LOADING";
export const TRANSACTION_GET_ERROR = "TRANSACTION_GET_ERROR";
export const TRANSACTION_GET_SUCCESS = "TRANSACTION_GET_SUCCESS";

export const TRANSACTION_GET_BY_ID_LOADING = "TRANSACTION_GET_BY_ID_LOADING";
export const TRANSACTION_GET_BY_ID_ERROR = "TRANSACTION_GET_BY_ID_ERROR";
export const TRANSACTION_GET_BY_ID_SUCCESS = "TRANSACTION_GET_BY_ID_SUCCESS";

export const TRANSACTION_POST_LOADING = "TRANSACTION_POST_LOADING";
export const TRANSACTION_POST_ERROR = "TRANSACTION_POST_ERROR";
export const TRANSACTION_POST_SUCCESS = "TRANSACTION_POST_SUCCESS";

export const TRANSACTION_UPDATE_LOADING = "TRANSACTION_UPDATE_LOADING";
export const TRANSACTION_UPDATE_ERROR = "TRANSACTION_UPDATE_ERROR";
export const TRANSACTION_UPDATE_SUCCESS = "TRANSACTION_UPDATE_SUCCESS";

// export const TRANSACTION_DELETE_LOADING = "TRANSACTION_DELETE_LOADING";
// export const TRANSACTION_DELETE_ERROR = "TRANSACTION_DELETE_ERROR";
// export const TRANSACTION_DELETE_SUCCESS = "TRANSACTION_DELETE_SUCCESS";