export const USER_GET_LOADING = "USER_GET_LOADING";
export const USER_GET_ERROR = "USER_GET_ERROR";
export const USER_GET_SUCCESS = "USER_GET_SUCCESS";

export const USER_POST_LOADING = "USER_POST_LOADING";
export const USER_POST_ERROR = "USER_POST_ERROR";
export const USER_POST_SUCCESS = "USER_POST_SUCCESS";

export const USER_UPDATE_LOADING = "USER_UPDATE_LOADING";
export const USER_UPDATE_ERROR = "USER_UPDATE_ERROR";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";