export const VENDOR_GET_LOADING = "VENDOR_GET_LOADING";
export const VENDOR_GET_ERROR = "VENDOR_GET_ERROR";
export const VENDOR_GET_SUCCESS = "VENDOR_GET_SUCCESS";

export const VENDOR_GET_BY_ID_LOADING = "VENDOR_GET_BY_ID_LOADING";
export const VENDOR_GET_BY_ID_ERROR = "VENDOR_GET_BY_ID_ERROR";
export const VENDOR_GET_BY_ID_SUCCESS = "VENDOR_GET_BY_ID_SUCCESS";

export const VENDOR_POST_LOADING = "VENDOR_POST_LOADING";
export const VENDOR_POST_ERROR = "VENDOR_POST_ERROR";
export const VENDOR_POST_SUCCESS = "VENDOR_POST_SUCCESS";

export const VENDOR_UPDATE_LOADING = "VENDOR_UPDATE_LOADING";
export const VENDOR_UPDATE_ERROR = "VENDOR_UPDATE_ERROR";
export const VENDOR_UPDATE_SUCCESS = "VENDOR_UPDATE_SUCCESS";

export const VENDOR_DELETE_LOADING = "VENDOR_DELETE_LOADING";
export const VENDOR_DELETE_ERROR = "VENDOR_DELETE_ERROR";
export const VENDOR_DELETE_SUCCESS = "VENDOR_DELETE_SUCCESS";