export const WEBSITE_GET_LOADING = "WEBSITE_GET_LOADING";
export const WEBSITE_GET_ERROR = "WEBSITE_GET_ERROR";
export const WEBSITE_GET_SUCCESS = "WEBSITE_GET_SUCCESS";

export const WEBSITE_POST_LOADING = "WEBSITE_POST_LOADING";
export const WEBSITE_POST_ERROR = "WEBSITE_POST_ERROR";
export const WEBSITE_POST_SUCCESS = "WEBSITE_POST_SUCCESS";

export const WEBSITE_UPDATE_LOADING = "WEBSITE_UPDATE_LOADING";
export const WEBSITE_UPDATE_ERROR = "WEBSITE_UPDATE_ERROR";
export const WEBSITE_UPDATE_SUCCESS = "WEBSITE_UPDATE_SUCCESS";

export const WEBSITE_SEND_LOADING = "WEBSITE_SEND_LOADING";
export const WEBSITE_SEND_ERROR = "WEBSITE_SEND_ERROR";
export const WEBSITE_SEND_SUCCESS = "WEBSITE_SEND_SUCCESS";