export const USER_AUTH_LOGIN_LOADING = "USER_AUTH_LOGIN_LOADING";
export const USER_AUTH_LOGIN_ERROR = "USER_AUTH_LOGIN_ERROR";
export const USER_AUTH_LOGIN_SUCCESS = "USER_AUTH_LOGIN_SUCCESS";
export const USER_LOGOUT = "USER_LOGOUT";

export const CARVENDOR_AUTH_LOGIN_LOADING = "CARVENDOR_AUTH_LOGIN_LOADING";
export const CARVENDOR_AUTH_LOGIN_ERROR = "CARVENDOR_AUTH_LOGIN_ERROR";
export const CARVENDOR_AUTH_LOGIN_SUCCESS = "CARVENDOR_AUTH_LOGIN_SUCCESS";
export const CARVENDOR_LOGOUT = "CARVENDOR_LOGOUT";

export const CUSTOMER_AUTH_LOGIN_LOADING = "CUSTOMER_AUTH_LOGIN_LOADING";
export const CUSTOMER_AUTH_LOGIN_ERROR = "CUSTOMER_AUTH_LOGIN_ERROR";
export const CUSTOMER_AUTH_LOGIN_SUCCESS = "CUSTOMER_AUTH_LOGIN_SUCCESS";
export const CUSTOMER_LOGOUT = "CUSTOMER_LOGOUT";

export const CUSTOMER_AUTH_SIGNUP_LOADING = "CUSTOMER_AUTH_SIGNUP_LOADING";
export const CUSTOMER_AUTH_SIGNUP_ERROR = "CUSTOMER_AUTH_SIGNUP_ERROR";
export const CUSTOMER_AUTH_SIGNUP_SUCCESS = "CUSTOMER_AUTH_SIGNUP_SUCCESS";
export const CUSTOMER_AUTH_UPDATE_SUCCESS = "CUSTOMER_AUTH_UPDATE_SUCCESS"
