export const IndianStates = [
    "Andhra Pradesh - AP",
    "Arunachal Pradesh - AR",
    "Assam - AS",
    "Bihar - BR",
    "Chhattisgarh - CG",
    "Goa - GA",
    "Gujarat - GJ",
    "Haryana - HR",
    "Himachal Pradesh - HP",
    "Jharkhand - JH",
    "Karnataka - KA",
    "Kerala - KL",
    "Madhya Pradesh - MP",
    "Maharashtra - MH",
    "Manipur - MN",
    "Meghalaya - ML",
    "Mizoram - MZ",
    "Nagaland - NL",
    "Odisha - OR",
    "Punjab - PB",
    "Rajasthan - RJ",
    "Sikkim - SK",
    "Tamil Nadu - TN",
    "Telangana - TG",
    "Tripura - TR",
    "Uttar Pradesh - UP",
    "Uttarakhand - UK",
    "West Bengal - WB",
    "Delhi - DL",
    "Jammu and Kashmir - JK",
    "Ladakh - LA",
    "Puducherry - PY",
    "Chandigarh - CH",
    "Dadra and Nagar Haveli and Daman and Diu - DN",
    "Lakshadweep - LD"
]