
export const CARMODEL_GET_LOADING = "CARMODEL_GET_LOADING";
export const CARMODEL_GET_ERROR = "CARMODEL_GET_ERROR";
export const CARMODEL_GET_SUCCESS = "CARMODEL_GET_SUCCESS";

export const CARMODEL_POST_LOADING = "CARMODEL_POST_LOADING";
export const CARMODEL_POST_ERROR = "CARMODEL_POST_ERROR";
export const CARMODEL_POST_SUCCESS = "CARMODEL_POST_SUCCESS";

export const CARMODEL_UPDATE_LOADING = "CARMODEL_UPDATE_LOADING";
export const CARMODEL_UPDATE_ERROR = "CARMODEL_UPDATE_ERROR";
export const CARMODEL_UPDATE_SUCCESS = "CARMODEL_UPDATE_SUCCESS";

export const CARMODEL_GET_BY_ID_LOADING = "CARMODEL_GET_BY_ID_LOADING";
export const CARMODEL_GET_BY_ID_ERROR = "CARMODEL_GET_BY_ID_ERROR";
export const CARMODEL_GET_BY_ID_SUCCESS = "CARMODEL_GET_BY_ID_SUCCESS";

export const CARMODEL_DELETE_LOADING = "CARMODEL_DELETE_LOADING";
export const CARMODEL_DELETE_ERROR = "CARMODEL_DELETE_ERROR";
export const CARMODEL_DELETE_SUCCESS = "CARMODEL_DELETE_SUCCESS";


export const MAKE_GET_LOADING = "MAKE_GET_LOADING";
export const MAKE_GET_ERROR = "MAKE_GET_ERROR";
export const MAKE_GET_SUCCESS = "MAKE_GET_SUCCESS";

export const MAKE_POST_LOADING = "MAKE_POST_LOADING";
export const MAKE_POST_ERROR = "MAKE_POST_ERROR";
export const MAKE_POST_SUCCESS = "MAKE_POST_SUCCESS";

export const MAKE_UPDATE_LOADING = "MAKE_UPDATE_LOADING";
export const MAKE_UPDATE_ERROR = "MAKE_UPDATE_ERROR";
export const MAKE_UPDATE_SUCCESS = "MAKE_UPDATE_SUCCESS";

export const MAKE_GET_BY_ID_LOADING = "MAKE_GET_BY_ID_LOADING";
export const MAKE_GET_BY_ID_ERROR = "MAKE_GET_BY_ID_ERROR";
export const MAKE_GET_BY_ID_SUCCESS = "MAKE_GET_BY_ID_SUCCESS";

export const MAKE_DELETE_LOADING = "MAKE_DELETE_LOADING";
export const MAKE_DELETE_ERROR = "MAKE_DELETE_ERROR";
export const MAKE_DELETE_SUCCESS = "MAKE_DELETE_SUCCESS";


export const BODYTYPE_GET_LOADING = "BODYTYPE_GET_LOADING";
export const BODYTYPE_GET_ERROR = "BODYTYPE_GET_ERROR";
export const BODYTYPE_GET_SUCCESS = "BODYTYPE_GET_SUCCESS";

export const BODYTYPE_POST_LOADING = "BODYTYPE_POST_LOADING";
export const BODYTYPE_POST_ERROR = "BODYTYPE_POST_ERROR";
export const BODYTYPE_POST_SUCCESS = "BODYTYPE_POST_SUCCESS";

export const BODYTYPE_UPDATE_LOADING = "BODYTYPE_UPDATE_LOADING";
export const BODYTYPE_UPDATE_ERROR = "BODYTYPE_UPDATE_ERROR";
export const BODYTYPE_UPDATE_SUCCESS = "BODYTYPE_UPDATE_SUCCESS";

export const BODYTYPE_GET_BY_ID_LOADING = "BODYTYPE_GET_BY_ID_LOADING";
export const BODYTYPE_GET_BY_ID_ERROR = "BODYTYPE_GET_BY_ID_ERROR";
export const BODYTYPE_GET_BY_ID_SUCCESS = "BODYTYPE_GET_BY_ID_SUCCESS";

export const BODYTYPE_DELETE_LOADING = "BODYTYPE_DELETE_LOADING";
export const BODYTYPE_DELETE_ERROR = "BODYTYPE_DELETE_ERROR";
export const BODYTYPE_DELETE_SUCCESS = "BODYTYPE_DELETE_SUCCESS";


export const COLOR_GET_LOADING = "COLOR_GET_LOADING";
export const COLOR_GET_ERROR = "COLOR_GET_ERROR";
export const COLOR_GET_SUCCESS = "COLOR_GET_SUCCESS";

export const COLOR_POST_LOADING = "COLOR_POST_LOADING";
export const COLOR_POST_ERROR = "COLOR_POST_ERROR";
export const COLOR_POST_SUCCESS = "COLOR_POST_SUCCESS";

export const COLOR_UPDATE_LOADING = "COLOR_UPDATE_LOADING";
export const COLOR_UPDATE_ERROR = "COLOR_UPDATE_ERROR";
export const COLOR_UPDATE_SUCCESS = "COLOR_UPDATE_SUCCESS";

export const COLOR_GET_BY_ID_LOADING = "COLOR_GET_BY_ID_LOADING";
export const COLOR_GET_BY_ID_ERROR = "COLOR_GET_BY_ID_ERROR";
export const COLOR_GET_BY_ID_SUCCESS = "COLOR_GET_BY_ID_SUCCESS";

export const COLOR_DELETE_LOADING = "COLOR_DELETE_LOADING";
export const COLOR_DELETE_ERROR = "COLOR_DELETE_ERROR";
export const COLOR_DELETE_SUCCESS = "COLOR_DELETE_SUCCESS";


export const LOCATION_GET_LOADING = "LOCATION_GET_LOADING";
export const LOCATION_GET_ERROR = "LOCATION_GET_ERROR";
export const LOCATION_GET_SUCCESS = "LOCATION_GET_SUCCESS";

export const LOCATION_POST_LOADING = "LOCATION_POST_LOADING";
export const LOCATION_POST_ERROR = "LOCATION_POST_ERROR";
export const LOCATION_POST_SUCCESS = "LOCATION_POST_SUCCESS";

export const LOCATION_UPDATE_LOADING = "LOCATION_UPDATE_LOADING";
export const LOCATION_UPDATE_ERROR = "LOCATION_UPDATE_ERROR";
export const LOCATION_UPDATE_SUCCESS = "LOCATION_UPDATE_SUCCESS";

export const LOCATION_GET_BY_ID_LOADING = "LOCATION_GET_BY_ID_LOADING";
export const LOCATION_GET_BY_ID_ERROR = "LOCATION_GET_BY_ID_ERROR";
export const LOCATION_GET_BY_ID_SUCCESS = "LOCATION_GET_BY_ID_SUCCESS";

export const LOCATION_DELETE_LOADING = "LOCATION_DELETE_LOADING";
export const LOCATION_DELETE_ERROR = "LOCATION_DELETE_ERROR";
export const LOCATION_DELETE_SUCCESS = "LOCATION_DELETE_SUCCESS";


export const CARNAME_GET_LOADING = "CARNAME_GET_LOADING";
export const CARNAME_GET_ERROR = "CARNAME_GET_ERROR";
export const CARNAME_GET_SUCCESS = "CARNAME_GET_SUCCESS";

export const CARNAME_SREACH_GET_LOADING = "CARNAME_SREACH_GET_LOADING";
export const CARNAME_SREACH_GET_ERROR = "CARNAME_SREACH_GET_ERROR";
export const CARNAME_SREACH_GET_SUCCESS = "CARNAME_SREACH_GET_SUCCESS";

export const CARNAME_POST_LOADING = "CARNAME_POST_LOADING";
export const CARNAME_POST_ERROR = "CARNAME_POST_ERROR";
export const CARNAME_POST_SUCCESS = "CARNAME_POST_SUCCESS";

export const CARNAME_UPDATE_LOADING = "CARNAME_UPDATE_LOADING";
export const CARNAME_UPDATE_ERROR = "CARNAME_UPDATE_ERROR";
export const CARNAME_UPDATE_SUCCESS = "CARNAME_UPDATE_SUCCESS";

export const CARNAME_GET_BY_ID_LOADING = "CARNAME_GET_BY_ID_LOADING";
export const CARNAME_GET_BY_ID_ERROR = "CARNAME_GET_BY_ID_ERROR";
export const CARNAME_GET_BY_ID_SUCCESS = "CARNAME_GET_BY_ID_SUCCESS";

export const CARNAME_DELETE_LOADING = "CARNAME_DELETE_LOADING";
export const CARNAME_DELETE_ERROR = "CARNAME_DELETE_ERROR";
export const CARNAME_DELETE_SUCCESS = "CARNAME_DELETE_SUCCESS";