export const CAR_GET_LOADING = "CAR_GET_LOADING";
export const CAR_GET_ERROR = "CAR_GET_ERROR";
export const CAR_GET_SUCCESS = "CAR_GET_SUCCESS";

export const CAR_POST_LOADING = "CAR_POST_LOADING";
export const CAR_POST_ERROR = "CAR_POST_ERROR";
export const CAR_POST_SUCCESS = "CAR_POST_SUCCESS";

export const CAR_UPDATE_LOADING = "CAR_UPDATE_LOADING";
export const CAR_UPDATE_ERROR = "CAR_UPDATE_ERROR";
export const CAR_UPDATE_SUCCESS = "CAR_UPDATE_SUCCESS";

export const CAR_GET_BY_ID_LOADING = "CAR_GET_BY_ID_LOADING";
export const CAR_GET_BY_ID_ERROR = "CAR_GET_BY_ID_ERROR";
export const CAR_GET_BY_ID_SUCCESS = "CAR_GET_BY_ID_SUCCESS";

export const CAR_DELETE_LOADING = "CAR_DELETE_LOADING";
export const CAR_DELETE_ERROR = "CAR_DELETE_ERROR";
export const CAR_DELETE_SUCCESS = "CAR_DELETE_SUCCESS";

export const LOCATION_LOADING = "LOCATION_LOADING";
export const LOCATION_SUCCESS = "LOCATION_SUCCESS";

